apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-exporter
  template:
    metadata:
      labels:
        app: minecraft-exporter
    spec:
      containers:
        - name: exporter
          image: ghcr.io/dirien/minecraft-exporter:latest
          args:
            - "--mc.server=minecraft-service:25565"
          ports:
            - containerPort: 9150
              name: metrics
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-exporter
  labels:
    app: minecraft-exporter
spec:
  ports:
    - port: 9150
      targetPort: 9150
      name: metrics
  selector:
    app: minecraft-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minecraft-exporter-monitor
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: minecraft-exporter
  endpoints:
    - port: metrics
      interval: 30s