apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret 
      containers:
        - name: minecraft-server
          image: YOUR_ECR_URL:YOUR_IMAGE_TAG
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: MOTD
              value: "Shankar Server"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          startupProbe:
            tcpSocket:
              port: 25565
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data-pvc