---
- name: Configure Minecraft Server
  hosts: minecraft
  become: yes
  vars:
    s3_bucket: "ops3-minecraft-world-data-20aee98a"
  tasks:
    - name: Download and install k3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure k3s service is running and enabled
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Ensure /data directory exists for world state
      file:
        path: /data
        state: directory
        mode: '0777'

    - name: Restore world data from S3 (Does not fail if bucket is empty)
      command: aws s3 sync s3://{{ s3_bucket }}/ /data/
      changed_when: false